language: cpp

cache: apt

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j2"

before_script:
    - mkdir build && cd build && CXX=g++-5 cmake ..

script:
    - make

os:
    - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - build-essential
            - libboost-dev
            - gcc-5
            - g++-5
            - cmake
            - qt5-default
            - qtbase5-dev-tools
