language: cpp

cache: apt

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j2"
    matrix:
        - QT_BASE=55
        - QT_BASE=56

sudo: required

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y; fi
    - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
    - sudo apt-get update -qq

install:
    - if [ "$QT_BASE" = "55" ]; then sudo apt-get install -qq qt55base qt55xmlpatterns qt55svg; source /opt/qt55/bin/qt55-env.sh; fi
    - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base qt56xmlpatterns qt56svg; source /opt/qt56/bin/qt56-env.sh; fi

before_script:
    - mkdir build && cd build && CXX=g++-5 CC=gcc-5 cmake -DQT_VERSION=Qt5 ..

script:
    - make

os:
    - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - build-essential
            - libboost-dev
            - gcc-5
            - g++-5
            - cmake3
